trigger:
- main  # Define the branch to trigger the pipeline on

pool: 'laptops'

variables:
  buildConfiguration: 'production'


steps:
- task: Npm@1
  inputs:
    command: 'install'
- script: |
    npm install
    npm run build-prod
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'