trigger:
- main  # Define the branch to trigger the pipeline on

pool: 'laptops'
#agent: 'dell'

variables:
  buildConfiguration: 'production'


steps:
- task: Npm@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Npm'
  
- script: |
    npm install
    npm run build-prod
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'