trigger:
- main  # Define the branch to trigger the pipeline on

pool: laptops
#agent: 'dell'

variables:
  buildConfiguration: 'production'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # This will install Node.js 14.x, which includes npm 6.x or higher
  displayName: 'Install Node.js'
  
- script: |
    npm install
    npm run build-prod
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'