trigger:
- main  # Define the branch to trigger the pipeline on

pool: laptops
#agent: 'dell'

variables:
  buildConfiguration: 'production'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # This will install Node.js 14.x, which includes npm 6.x or higher
  displayName: 'Install Node.js'
  
- script: |
    registry=https://pkgs.dev.azure.com/aslairlinegcp/_packaging/aslairlinegcp/npm/registry/always-auth=true
    vsts-npm-auth -config .npmrc
    npm install
    npm run build-prod
    npm publish
  displayName: 'Build Angular App'



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'